In [2]:
import Code
ss=Code.get_sample_size(0.05,.20,0.05,0.2)
print(ss)

25255.0

C:\Users\ACER\Desktop\fittly\ab testing\Code.py:93: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  pivoted = filtered_df.groupby(['KPI']).sum().drop(labels = 'cookies',axis = 1).transpose()

In [3]:
import pandas as pd
import scipy.stats as stat
import math
import numpy as np
from datetime import datetime

In [4]:
print("hello")

hello

In [10]:
df = pd.read_csv("Test_1.csv")
df.event_date = pd.to_datetime(df.event_date)

In [11]:
df.head()

,event_date,grouped_page_name,Device,country_name,cookies,KPI,Values
0,2021-08-26,nfp,Mobile,OTHERS,0,#_Merchant_Signup_Complete,4
1,2021-08-28,nfp,Mobile,US,0,#_Merchant_Signup_Complete,2
2,2021-08-25,nfp,Mobile,OTHERS,0,#_Merchant_Signup_Complete,2
3,2021-08-27,nfp,Mobile,OTHERS,0,#_Merchant_Signup_Complete,2
4,2021-08-31,nfp,Mobile,OTHERS,0,#_Merchant_Signup_Complete,1

In [18]:
!pip install --upgrade pandas

Requirement already satisfied: pandas in c:\users\acer\anaconda3\lib\site-packages (1.5.3)
Requirement already satisfied: numpy>=1.20.3 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (1.22.4)
Requirement already satisfied: pytz>=2020.1 in c:\users\acer\appdata\roaming\python\python39\site-packages (from pandas) (2022.7)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\acer\appdata\roaming\python\python39\site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\acer\appdata\roaming\python\python39\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [21]:
import pandas.io.formats.style

ModuleNotFoundError: No module named 'pandas.io.formats.style'

In [20]:
def highlight(x):
    df=x.copy()
    df[['event_date', 'Device']] = 'background-color: grey'
display(df.style.apply(highlight_cols, axis = None))

ModuleNotFoundError: No module named 'pandas.io.formats.style'

In [13]:
df

,event_date,grouped_page_name,Device,country_name,cookies,KPI,Values
0,background-color: grey,nfp,background-color: grey,OTHERS,0,#_Merchant_Signup_Complete,4
1,background-color: grey,nfp,background-color: grey,US,0,#_Merchant_Signup_Complete,2
2,background-color: grey,nfp,background-color: grey,OTHERS,0,#_Merchant_Signup_Complete,2
3,background-color: grey,nfp,background-color: grey,OTHERS,0,#_Merchant_Signup_Complete,2
4,background-color: grey,nfp,background-color: grey,OTHERS,0,#_Merchant_Signup_Complete,1
...,...,...,...,...,...,...,...
13555,background-color: grey,Enterprise Pages,background-color: grey,OTHERS,0,#_Raw_Prospects,27
13556,background-color: grey,for_you_transfer_money_send_money,background-color: grey,OTHERS,0,#_Raw_Prospects,27
13557,background-color: grey,business_platforms_and_marketplaces,background-color: grey,OTHERS,0,#_Raw_Prospects,27
13558,background-color: grey,nfp,background-color: grey,OTHERS,0,#_Raw_Prospects,27
13559,background-color: grey,enterprise_manage_risk,background-color: grey,OTHERS,0,#_Raw_Prospects,27

In [8]:
pages = df.grouped_page_name.unique() #Unique page names
countries = df.country_name.unique()  #Unique country names
devices = df.Device.unique()          #Unique Device names
cookies = df.cookies.unique()         #Unique cookie names
min_date = df.event_date.min()        #Getting the earliest date in the dataset
max_date = df.event_date.max()
print(pages,"\n\n",countries,"\n\n",devices,"\n\n",cookies,"\n\n",min_date,"\n\n",max_date,"\n\n")

['nfp' 'Others' 'brcHome' 'SMB Pages' 'merchant_fees' 'Consumer Pages'
 'Enterprise Pages' 'PayPal Home Page' 'how_paypal_works'
 'money_management' 'BUSINESS HOME PAGE' 'product:pay_online'
 'enterprise_platform' 'business_manage_risk' 'business_make_payments'
 'enterprise_manage_risk' 'mobile_apps_paypal_app'
 'business_accept_payments' 'business_getting_started'
 'enterprise_make_paymentsS' 'business_accelerate_growth'
 'enterprise_accelerate_growth' 'credit_line_and_card_services'
 'business_streamline_operations' 'enterprise_streamline_operations'
 'for_you_transfer_money_send_money' 'business_platforms_and_marketplaces']

 ['OTHERS' 'US']

 ['Mobile' 'OTHERS' 'Desktop']

 [0]

 2021-08-25 00:00:00

 2021-08-31 00:00:00

In [9]:
MDE = 0.01                           # Minimum Detectable effect
start = pd.to_datetime("2021-08-26") # The earliest date the user wants (should be less than max_date)
end = pd.to_datetime("2021-08-29")   # The oldest date the user wants (should be more than min_date)
days = (end - start).days            # The no days between start and end
ramp = pd.to_datetime("2021-09-01")  # The day when the treatment will be fully activated
lift = 0.01                          # The amount of increse in conversion rates that the user expects 
Metric = "Raw Prospector"            # The Metric with respect to which all the calculations are performed (The selected Metric/The Denominator Metric)
pagename = 'PayPal Home Page'        # The page selected for calculation
country = "US"                       # The country selected for the calculations
device = ['Mobile','OTHERS','Desktop'] # The device selected for the calculations
cookie = 0                           # The cookie selected for calculations

# The various metrics that can be selected
Metrics = ["Visitor","Raw Prospector","Qualified Prospector","Signup Start","Signup Complete"]
m = Metrics.index(Metric) # The index of the selected Metric (The denominator Metric)

In [11]:
print(days)

3

In [46]:
get_sample_size(0.20,0.05)

7663.0

In [12]:
def get_sample_size(mde, baseline_val,alpha = 0.05, beta = 0.2,relative=True):
    """
    Calculates the MSS of an experiment given the significance level, beta which determines power of test,
    minimum detectable effect, baseline conversion rate and whether change is relative or absolute.
    
    Parameters:
    alpha(percentage): level of significance
    beta (percentage): statistical power is 1-beta
    mde: minimum detectable effect
    baseline_val: conversion rate of the control group

    Output:
    The number of days needed to conduct the test, given the input parameters.
    """
    # https://stats.stackexchange.com/questions/392979/ab-test-sample-size-calculation-by-hand
    conf = alpha/2 # for two-tailed test, we need to split alpha by 2, for either side
    z_a = stat.norm.ppf(conf) # z-score of alpha/2
    z_b = stat.norm.ppf(beta) # z-score of beta
    p1 = baseline_val
    if relative:
        p2 = p1 + p1*mde
    else:
        p2 = p1 + mde
    
    num = z_a*math.sqrt(2*p1*(1-p1)) + z_b*math.sqrt(p1*(1-p1) + p2*(1-p2))
    num = num**2
    den = (p2-p1)**2
    
    return num//den

In [31]:
sample_sizes={}
for i in range(1,16):
    mde=i/100
    baseline_val=0.20
    ss=get_sample_size(mde, baseline_val,alpha = 0.05, beta = 0.2,relative=True)
    sample_sizes[mde]=ss

In [53]:
df=pd.DataFrame([sample_sizes]).T.reset_index()
df['Alpha']=0.5
df['Beta']=0.8
df.columns=['MDE','Sample Size','Alpha','Beta']
df

     MDE  Sample Size  Alpha  Beta
0   0.01     628614.0    0.5   0.8
1   0.02     157328.0    0.5   0.8
2   0.03      70000.0    0.5   0.8
3   0.04      39418.0    0.5   0.8
4   0.05      25255.0    0.5   0.8
5   0.06      17557.0    0.5   0.8
6   0.07      12912.0    0.5   0.8
7   0.08       9896.0    0.5   0.8
8   0.09       7827.0    0.5   0.8
9   0.10       6347.0    0.5   0.8
10  0.11       5250.0    0.5   0.8
11  0.12       4416.0    0.5   0.8
12  0.13       3767.0    0.5   0.8
13  0.14       3251.0    0.5   0.8
14  0.15       2835.0    0.5   0.8

In [13]:
# This function filters the data from the CSV according to the filter values
# Inputs:
# df : The dataframe read from the CSV file
# start_date, end_date, country, pagenames, device_type, cookies : The different parameters we want to filter out

#Output:
# A Dataframe that only contains the data within the constraints provided by the user

def filter_data(df, start_date, end_date, country, pagenames, device_type, cookies):
    filtered_df = df[(df['event_date']>= start_date) & (df['event_date']<= end_date) \
                & (df['country_name'] == country) & (df['grouped_page_name'] == pagenames) \
                & (df['Device'].isin(device_type)) & (df['cookies'] == cookies) ] 
    return filtered_df

# Testing the filter_data function
fl = filter_data(df, start, end, country, pagename, device, cookie)
fl.head(5)

,event_date,grouped_page_name,Device,country_name,cookies,KPI,Values
100,2021-08-28,PayPal Home Page,Mobile,US,0,#_Merchant_Signup_Complete,980
103,2021-08-29,PayPal Home Page,Mobile,US,0,#_Merchant_Signup_Complete,864
109,2021-08-27,PayPal Home Page,Mobile,US,0,#_Merchant_Signup_Complete,971
110,2021-08-26,PayPal Home Page,Mobile,US,0,#_Merchant_Signup_Complete,915
477,2021-08-29,PayPal Home Page,OTHERS,US,0,#_Merchant_Signup_Complete,15

In [17]:
# This function counts all the KPI values and selects the KPI values based on the funnel type selected
# Inputs
# filtered_df: The dataframe that has already been filtered
# funnel_type : The funnel type we want, options: "overall", "merchant", "consumer"

#Output:
# A pivoted DataFrame that counts the values of the Selected KPI's we want
def pivot_data(filtered_df,funnel_type = "overall"):
    # We first count all the KPI values after grouping by KPI
    pivoted = filtered_df.groupby(['KPI']).sum().drop(labels = 'cookies',axis = 1).transpose()
    if funnel_type == 'overall': # overall funnel ignores merchant and consumer KPIs
        pivoted = pivoted[['#_Visitors','#_Raw_Prospects','#_QLFD_Prospects','#_Signup_Start','#_Signup_Complete','#_Active_7_Days']]
    elif funnel_type == 'merchant': # merchant funnel only selects merchant KPIs
        pivoted = pivoted[['#_Visitors','#_Raw_Prospects','#_QLFD_Prospects','#_Merchant_Signup_Start','#_Merchant_Signup_Complete','#_Merchant_Active_7_Days']]
    elif funnel_type == 'consumer': # consumer funnel only selects consumer KPIs
        pivoted = pivoted[['#_Visitors','#_Raw_Prospects','#_QLFD_Prospects','#_Consumer_Signup_Start','#_Consumer_Signup_Complete','#_Consumer_Active_7_Days']]
    return pivoted   
    
# Testing the pivot_data function
pt = pivot_data(fl,'overall')
pt

C:\Users\ACER\AppData\Local\Temp\ipykernel_6092\1292997676.py:10: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  pivoted = filtered_df.groupby(['KPI']).sum().drop(labels = 'cookies',axis = 1).transpose()

KPI,#_Visitors,#_Raw_Prospects,#_QLFD_Prospects,#_Signup_Start,#_Signup_Complete,#_Active_7_Days
Values,958562,860849,308089,176899,145601,37443

In [18]:
# This function gives us the calculted conversion rate with respect to the selected Metic (The denominator Metric)
# Inputs
# pivoted_df : The Dataframe containing the counts of different KPIs
# m : The index of selected Metric

#Output:
# A Dataframe that calculates the conversion rate with respect to the selected Metric

def conversions_data(pivoted_df,m):
    # The list that contains the names of various Mterics in a short form
    Met = ['Visitors', 'RP', 'QP', 'SS', 'SC', 'Activations']
    conversions = pd.DataFrame() # We create an empty DataFrame
    for i in range(m,5): # We start from selected Metric to the the end of the pivoted DataFrame
        # the conversion rate is calculated as percentage of the smaller KPI from the selected KPI (The selected Metic/The denominator Metric)
        conversions[Met[i+1]+'/'+Met[m]] = pd.Series(round(pivoted_df.iloc[0,i+1] * 100 / pivoted_df.iloc[0,m],2))
    return conversions
    
# Testing the conversions_data function
con = conversions_data(pt,m)
con

   QP/RP  SS/RP  SC/RP  Activations/RP
0  35.79  20.55  16.91            4.35

In [19]:
# This is a simple function that takes in sample size, the total KPI count and days between start and end to return the duration (in days) it will take for the eperiment
def test_duration(sample_size, total, days):
    avg = total/days
    return(sample_size//avg)

In [20]:
# This function helps us calculate the Minimum Sample Size and the duration (in Days and Weeks) it will take to complete the experiment
# Inputs:
# MDE : Minimum Detectable Effect
# conversion_df: The DataFrame containg the conversion rate for the various metrics (KPIs) with respect to the selected Metric
# pivoted_df : The DataFRame containg the KPI counts for select KPIs
# m : index of the Metric selected
# days : The days between the selected starting day and the ending day

# Output: A dataframe with a row containg the conversion, rate, sample size, Days and weeks for each Metric conversion
def sizing(mde, conversion_df, pivoted_df, m, days):
    col = conversion_df.shape[1] # We take the no columns in conversion_df to know the no of metrics we may need
    sizing_df = pd.DataFrame() # We create an Empty DataFrame
    # We add empty columns to the DataFrame
    sizing_df[["Metrics","Conversion","Sample Size","Days","Weeks"]] = ""
    for i in range(col): 
        m = m+1 # We advance the Metric by one (here both m and i refer to same metric but in different DataFames: pivoted and convesion_df)
        ss = [] # We create an empty list
        ss.append(conversion_df.columns[i]) # Metrics We add the Metric name from conversion_df to the list
        ss.append(conversion_df.iloc[0,i])  # The conversion of the Metric
        ss.append(get_sample_size(mde,(conversion_df.iloc[0,i]/100)))  # The calculated sample size for the Mteric
        ss.append(test_duration(ss[2], pivoted_df.iloc[0,m],days))  # The duration of the Experiment in days
        ss.append(round(ss[3]/7,2)) # The duration in Weeks
        sizing_df.loc[i] = ss # We attach the list as a row in the DataFame
    return sizing_df

# Testing the sizing function
ss = sizing(MDE,con,pt,m,days)
ss

          Metrics  Conversion  Sample Size   Days  Weeks
0           QP/RP       35.79     281814.0    2.0   0.29
1           SS/RP       20.55     607576.0   10.0   1.43
2           SC/RP       16.91     772254.0   15.0   2.14
3  Activations/RP        4.35    3456645.0  276.0  39.43

In [22]:
# This function calculates the the amount of conversions (Activations) we can get for a given amount of lift
# MDE : Minimum Detectable Effect
# conversion_df: The DataFrame containg the conversion rate for the various metrics (KPIs) with respect to the selected Metric
# lift : The supposed increase in the conversion rate that the user enters
# pivoted_df : The DataFRame containg the KPI counts for select KPIs
# m : index of the Metric selected
# days : The days between the selected starting day and the ending day

#Output
# A DataFrame that calculates the conversions (Activations) we can expect for a given lift on a Daily Basis, Yearly Basis and By the end of the year after the treatment is ramped

def get_nna(ramp, conversion_df, lift, pivoted, m, days): #
    col = conversion_df.shape[1] # We take the no columns in conversion_df to know the no of metrics we may need
    eoy = pd.to_datetime(str(ramp.year)+"-12-31") # We get the end of the year from ramped date
    ramped_days = (eoy - ramp).days # We calculate the no of days from ramped date to end of the year
    activations_df = pd.DataFrame() # We create an Empty DataFrame
    # We add empty columns to the DataFrame
    activations_df[["Metrics","Activations(Daily)","Activations(Yearly)","Activations(Year End)"]] = ""
    daily_rate = pivoted.iloc[0,m]/days # The daily conversions of the denominator Metric (The selected Metric)
    for i in range(col):
        ac = [] # We create an empty list
        base = conversion_df.iloc[0,i]/100 # We get the conversion for a given Metric and divide it by 100 to get it in decimal points
        ac.append(conversion_df.columns[i]) # We take the name of the Metic
        ac.append(math.ceil(daily_rate * lift * base)) # We calculate the expected daily conversions for the Metic using lift
        ac.append(ac[1] * 365) # We calculate the Yearly conversions using the daily conversions
        ac.append(ac[1] * ramped_days) # We calculate the conversions by the end of the Year
        activations_df.loc[i] = ac #We attach the list as row to the DataFrame
    return activations_df

# Testing the NNA function
get_nna(ramp, con, lift, pt, m, days)

,Metrics,Activations(Daily),Activations(Yearly),Activations(Year End)
0,QP/RP,1027,374855,124267
1,SS/RP,590,215350,71390
2,SC/RP,486,177390,58806
3,Activations/RP,125,45625,15125

In [23]:
# This function calculates the conversion rate for the subsequent funnels (very different to conversions_data() as that only calculates conversion rates with respect to a selected Metric)
def funnel_data(pivoted):
    funnel = pd.DataFrame() # We create an Empty DataFrame
    col = pivoted.shape[1]  # We take the no of columns in pivoted to know the no of metrics we may need
    funnel["#_Visitors"] = [100.00] # We set Visitors as 100% because it is the parent funnel to all funnels
    for i in range(1,col):
        # We calculate the conversion rate as pecentage of KPI counts of the child funnel to its parent funnel
        funnel[pivoted.columns[i]] = [round(pivoted.iloc[0,i] * 100 / pivoted.iloc[0,i-1],2)]
    return funnel   
funnel_data(pt)

,#_Visitors,#_Raw_Prospects,#_QLFD_Prospects,#_Signup_Start,#_Signup_Complete,#_Active_7_Days
0,100.0,89.81,35.79,57.42,82.31,25.72